
# resolver: lts-8.23

packages:
- '.'

extra-deps:
  - compact-0.1.0.1
  - primitive-0.6.2.0
  - random-1.1
  - QuickCheck-2.10.0.1
  - hspec-2.4.4
  - QuickCheck-2.10.0.1
  - hspec-2.4.4
  - HUnit-1.6.0.0
  - call-stack-0.1.0
  - hspec-core-2.4.4
  - hspec-discover-2.4.4
  - hspec-expectations-0.8.2
  - tf-random-0.5
  - ansi-terminal-0.6.3.1
  - async-2.1.1.1
  - quickcheck-io-0.2.0
  - setenv-0.1.1.3
  - stm-2.4.4.1

flags: {}

extra-package-dbs: []

compiler: ghc-8.2.0.20170704
compiler-check: match-exact

resolver: ghc-8.2.0.20170704

setup-info:
  ghc:

    linux64:
      8.2.0.20170704:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc3/ghc-8.2.0.20170704-x86_64-deb8-linux.tar.xz
        content-length: 138482820
        sha1: ac1598c21ea2936b091885a29a0f5725668aaed5

    macosx:
      8.2.0.20170704:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc3/ghc-8.2.0.20170704-x86_64-apple-darwin.tar.xz
        content-length: 125197252
        sha1: 81e3093b559b9aaf8af2a89f182539849539cbe1

    windows64:
      8.2.0.20170704:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc3/ghc-8.2.0.20170704-x86_64-unknown-mingw32.tar.xz
        content-length: 175463160
        sha1: 3648302c66769d4aa0c3a9f82be4538f402f234f
